[workspace]
members = [
    "llm-chain",
    "llm-chain-openai",
    "llm-chain-llama",
    "llm-chain-llama/sys",
    "llm-chain-local",
    "llm-chain-qdrant",
]

[workspace.metadata.release]
shared-version = true
