[workspace]
members = ["crates/*"]

[workspace.metadata.release]
shared-version = true

[patch.crates-io]
hnsw_rs = { git = "https://github.com/ruqqq/hnswlib-rs" }
tiktoken-rs = { git = "https://github.com/DaviRain-Su/tiktoken-rs.git", branch = "main" }
