[package]
name = "llm-chain-milvus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.74"
llm-chain = { path = "../llm-chain", version = "0.12.3", default-features = false }
serde = "1.0.164"
serde_json = "1.0.99"
thiserror = "1.0.40"
uuid = "1.3.3"
milvus-sdk-rust = "0.1.0"

[dev-dependencies]
llm-chain-openai = { path = "../llm-chain-openai" }
tokio = "1.28.2"
serde_yaml = "0.9.21"
rand = "0.8.5"